[book]
authors = ["LuoYuDian" ,"MainPage"]
language = "zh-CN"
multilingual = false
src = "src"
title = "LuoYuDian的个人主页"

[output.html]
git-repository-url = "https://github.com/LuoYuDian/MianPage.git"
git-repository-icon = "fa-github"

[output.html.search]
enable = false
